export default class HistoricoVendas {
  constructor(
    readonly Empresa: string,
    readonly Filial: string,
    readonly Vendedor: string,
    readonly Dt_venda_fat: Date,
    readonly Doc_NF: string,
    readonly Tipo_Mov_Fiscal: string,
    readonly Estado_Veiculo: string,
    readonly Dias_Estoque: number,
    readonly ID_Cliente: string,
    readonly Nome_Cliente: string,
    readonly Mod_Tipo: string,
    readonly Veic_mod_grupo: string,
    readonly Categoria_Familia: string,
    readonly Ano_Fabr: number,
    readonly Ano_mod: number,
    readonly Cor: string,
    readonly Placa_Veic: string,
    readonly KM_Veic: number,
    readonly Tipo_Venda: string,
    readonly Vlr_Venda: number,
    readonly Vlr_Financ: number,
    readonly Qtde_Meses_Financ: number,
    readonly Vlr_Parc_Financ: number,
    readonly Motivo_Compra: string,
    readonly Taxa_Juros: number,
    readonly Chassis: string,
    readonly Renavam: string,
    readonly Vlr_Aquisicao: number,
    readonly Vlr_Sugerido: number,
    readonly Marca: string,
    readonly Endereco: string,
    readonly Endereco_Num: number,
    readonly Endereco_Compl: string,
    readonly Endereco_Bairro: string,
    readonly Endereco_CEP: string,
    readonly Endereco_Munic_estado: string,
    readonly email: string,
    readonly Telef_Cel: string,
    readonly Telef_Com: string,
    readonly Telef_Res: string,
    readonly Dt_Nascimento: Date,
    readonly Status_Historico: boolean
  ) {}
}
